version : '3'
services:
    web:
        container_name: docker-mysql
        restart: always
        build: .
        ports: 
            - '5000:5000'
        links: 
            - mysql
    mysql:
        container_name: mysql
        image: mysql:latest
        ports:
            - 3306:3306
    